POST http://localhost:5188/api/auth/token/
Accept: application/json
Content-Type: application/json
x-api-key: 

{
    "Email": "",
    "Password": "",
    "ClientId": "",
    "ClientSecret": "",
    "GrantType": ""
}
